// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "8ef97eb1-9bae-4bfb-a6ef-349adb3dd872");
user_pref(
  "app.update.background.previous.reasons",
  '["unsupported OS","not default profile"]',
);
user_pref(
  "app.update.lastUpdateTime.addon-background-update-timer",
  1727459593,
);
user_pref("app.update.lastUpdateTime.background-update-timer", 1727482246);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1727482246);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1727482246);
user_pref("app.update.lastUpdateTime.region-update-timer", 1727459593);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1727482216);
user_pref(
  "app.update.lastUpdateTime.services-settings-poll-changes",
  1727459593,
);
user_pref("app.update.lastUpdateTime.suggest-ingest", 1727459565);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1727459623);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1727459593);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.aboutwelcome.didSeeFinalScreen", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref(
  "browser.contextual-services.contextId",
  "{1d48cab7-a118-479f-b429-97ca164fc5f4}",
);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.fxa-toolbar-menu-button.has-used", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1727459563);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 149);
user_pref(
  "browser.newtabpage.activity-stream.discoverystream.rec.impressions",
  '{"8184875165326309":1727459582437,"4178810252074633":1727459582439,"3489322936344850":1727459587646,"5932397104988546":1727459587647,"6002397199596848":1727459587647,"8075834921481200":1727475796955,"7637245874835224":1727475796956,"3750454137458937":1727475796957,"2730453228828718":1727475796957,"844877708598823":1727477923349,"5911377383830746":1727477923349,"1556780316295404":1727477923350}',
);
user_pref(
  "browser.newtabpage.activity-stream.discoverystream.spoc.impressions",
  '{"608726097":[1727477923350,1727478682216,1727478751870,1727478801053,1727478881744,1727479021927]}',
);
user_pref(
  "browser.newtabpage.activity-stream.impressionId",
  "{5d4ef68e-9690-4464-9f55-b2e486821901}",
);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref(
  "browser.pageActions.persistedActions",
  '{"ids":["bookmark"],"idsInUrlbar":["bookmark"],"idsInUrlbarPreProton":[],"version":1}',
);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1727459565);
user_pref(
  "browser.safebrowsing.provider.google4.lastupdatetime",
  "1727482217497",
);
user_pref(
  "browser.safebrowsing.provider.google4.nextupdatetime",
  "1727484035497",
);
user_pref(
  "browser.safebrowsing.provider.mozilla.lastupdatetime",
  "1727482220401",
);
user_pref(
  "browser.safebrowsing.provider.mozilla.nextupdatetime",
  "1727503820401",
);
user_pref("browser.search.newSearchConfig.enabled", true);
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20240913135723");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.defaultBrowserCheckCount", 1);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20240913135723");
user_pref("browser.startup.homepage_override.mstone", "130.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1727482216);
user_pref(
  "browser.uiCustomization.state",
  '{"placements":{"widget-overflow-fixed-list":[],"unified-extensions-area":[],"nav-bar":["back-button","forward-button","stop-reload-button","customizableui-special-spring1","urlbar-container","customizableui-special-spring2","save-to-pocket-button","downloads-button","fxa-toolbar-menu-button","unified-extensions-button"],"TabsToolbar":["firefox-view-button","tabbrowser-tabs","new-tab-button","alltabs-button"],"PersonalToolbar":["import-button","personal-bookmarks"]},"seen":["save-to-pocket-button","developer-button"],"dirtyAreaCache":["nav-bar","PersonalToolbar","TabsToolbar"],"currentVersion":20,"newElementCount":2}',
);
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("browser.warnOnQuitShortcut", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref(
  "datareporting.policy.dataSubmissionPolicyNotifiedTime",
  "1727459565197",
);
user_pref("devtools.everOpened", true);
user_pref("devtools.toolbox.footer.height", 999);
user_pref("devtools.toolbox.selectedTool", "webconsole");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.iniFile.exists.appversion", "130.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("doh-rollout.mode", 2);
user_pref("doh-rollout.self-enabled", true);
user_pref("doh-rollout.uri", "https://mozilla.cloudflare-dns.com/dns-query");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "cc1117f9bc94461581f8a13af6ed2418");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref(
  "extensions.formautofill.creditCards.reauth.optout",
  "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECCLEr31EWQd7BAiSBN0D7S6NYw==",
);
user_pref("extensions.getAddons.cache.lastUpdate", 1727459593);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240913135723");
user_pref("extensions.lastAppVersion", "130.0.1");
user_pref("extensions.lastPlatformVersion", "130.0.1");
user_pref("extensions.pendingOperations", false);
user_pref(
  "extensions.pictureinpicture.enable_picture_in_picture_overrides",
  true,
);
user_pref(
  "extensions.quarantinedDomains.list",
  "autoatendimento.bb.com.br,ibpf.sicredi.com.br,ibpj.sicredi.com.br,internetbanking.caixa.gov.br,www.ib12.bradesco.com.br,www2.bancobrasil.com.br",
);
user_pref("extensions.systemAddonSet", '{"schema":1,"addons":{}}');
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref(
  "extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org",
  true,
);
user_pref(
  "extensions.webextensions.uuids",
  '{"formautofill@mozilla.org":"4b338f14-4eb9-439e-89fe-46fbd74de38c","pictureinpicture@mozilla.org":"9f5bd28d-a7a4-46b9-b8d8-af443e91d735","screenshots@mozilla.org":"0f9490c3-a23a-4841-96bf-34c0ef1d71a8","webcompat-reporter@mozilla.org":"56d09422-ca06-4dad-a6ac-9b40b7acbe68","webcompat@mozilla.org":"ca0f804e-40f9-4e86-bbb5-038e6616ee4b","default-theme@mozilla.org":"a0ecc997-7c86-4e3a-a149-b831c69fed05","addons-search-detection@mozilla.com":"423ac5e9-dbcc-4060-a56a-718b098a9a56"}',
);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("identity.fxaccounts.telemetry.clientAssociationPing.enabled", true);
user_pref("idle.lastDailyNotification", 1727460232);
user_pref("media.devices.insecure.enabled", true);
user_pref("media.getusermedia.insecure.enabled", true);
user_pref("media.gmp-gmpopenh264.abi", "aarch64-gcc3");
user_pref(
  "media.gmp-gmpopenh264.hashValue",
  "391efb184373d533713a9e99a9e63c3bbaf614e8d8bdfdd84d4d5e53b9a737e75032187309dd00e58b58bb1033ab68d199f994744f6add57dd08f5fbb654d2f3",
);
user_pref("media.gmp-gmpopenh264.lastDownload", 1727459594);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1727459594);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1727459594);
user_pref("media.gmp-gmpopenh264.version", "2.3.2");
user_pref("media.gmp-manager.buildID", "20240913135723");
user_pref("media.gmp-manager.lastCheck", 1727459610);
user_pref("media.gmp-manager.lastEmptyCheck", 1727459610);
user_pref("media.gmp-widevinecdm.abi", "aarch64-gcc3");
user_pref(
  "media.gmp-widevinecdm.hashValue",
  "b960132db31c5ca04f678992a970d415deae3dc8f90b37c61d2d4b67e7a41588f69c08c59476f0a92c765f0d18733bc90ee0786eece936122007a51e609020d6",
);
user_pref("media.gmp-widevinecdm.lastDownload", 1727459594);
user_pref("media.gmp-widevinecdm.lastInstallStart", 1727459594);
user_pref("media.gmp-widevinecdm.lastUpdate", 1727459595);
user_pref("media.gmp-widevinecdm.version", "4.10.2830.0");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.navigator.streams.fake", true);
user_pref(
  "media.videocontrols.picture-in-picture.video-toggle.first-seen-secs",
  1727475761,
);
user_pref(
  "nimbus.syncdefaultsstore.pocketNewtab",
  '{"slug":"newtab-recommendations-merino-migration","branch":{"slug":"control","ratio":1,"feature":{"value":null,"enabled":true,"featureId":"pocketNewtab"},"features":null},"active":true,"experimentType":"rollout","source":"rs-loader","userFacingName":"newtab recommendations merino migration","userFacingDescription":"Migrating newtab recommendations provider.","lastSeen":"2024-09-27T17:52:45.442Z","featureIds":["pocketNewtab"],"prefs":[],"isRollout":true}',
);
user_pref("nimbus.syncdefaultsstore.pocketNewtab.merinoProviderEnabled", true);
user_pref(
  "nimbus.syncdefaultsstore.upgradeDialog",
  '{"slug":"upgrade-spotlight-rollout","branch":{"slug":"treatment","ratio":1,"feature":{"value":null,"enabled":true,"featureId":"upgradeDialog"},"features":null},"active":true,"experimentType":"rollout","source":"rs-loader","userFacingName":"Upgrade Spotlight Rollout","userFacingDescription":"Experimenting on onboarding content when you upgrade Firefox.","lastSeen":"2024-09-27T17:52:45.397Z","featureIds":["upgradeDialog"],"prefs":[],"isRollout":true}',
);
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("permissions.default.camera", 1);
user_pref("permissions.default.microphone", 1);
user_pref("places.database.lastMaintenance", 1727460232);
user_pref(
  "privacy.bounceTrackingProtection.hasMigratedUserActivationData",
  true,
);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1727460232239");
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref(
  "services.settings.blocklists.addons-bloomfilters.last_check",
  1727482217,
);
user_pref("services.settings.blocklists.gfx.last_check", 1727482217);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", '"1727481670415"');
user_pref("services.settings.last_update_seconds", 1727482217);
user_pref(
  "services.settings.main.addons-manager-settings.last_check",
  1727482217,
);
user_pref(
  "services.settings.main.anti-tracking-url-decoration.last_check",
  1727482217,
);
user_pref("services.settings.main.cfr.last_check", 1727482217);
user_pref(
  "services.settings.main.cookie-banner-rules-list.last_check",
  1727482217,
);
user_pref(
  "services.settings.main.devtools-compatibility-browsers.last_check",
  1727482217,
);
user_pref("services.settings.main.devtools-devices.last_check", 1727482217);
user_pref("services.settings.main.doh-config.last_check", 1727482217);
user_pref("services.settings.main.doh-providers.last_check", 1727482217);
user_pref(
  "services.settings.main.fingerprinting-protection-overrides.last_check",
  1727482217,
);
user_pref("services.settings.main.hijack-blocklists.last_check", 1727482217);
user_pref(
  "services.settings.main.language-dictionaries.last_check",
  1727482217,
);
user_pref("services.settings.main.message-groups.last_check", 1727482217);
user_pref("services.settings.main.newtab-wallpapers-v2.last_check", 1727482217);
user_pref(
  "services.settings.main.nimbus-desktop-experiments.last_check",
  1727482217,
);
user_pref(
  "services.settings.main.nimbus-secure-experiments.last_check",
  1727482217,
);
user_pref(
  "services.settings.main.normandy-recipes-capabilities.last_check",
  1727482217,
);
user_pref(
  "services.settings.main.partitioning-exempt-urls.last_check",
  1727482217,
);
user_pref("services.settings.main.password-recipes.last_check", 1727482217);
user_pref("services.settings.main.password-rules.last_check", 1727482217);
user_pref(
  "services.settings.main.personality-provider-models.last_check",
  1727482217,
);
user_pref(
  "services.settings.main.personality-provider-recipe.last_check",
  1727482217,
);
user_pref(
  "services.settings.main.pioneer-study-addons-v1.last_check",
  1727482217,
);
user_pref("services.settings.main.query-stripping.last_check", 1727482217);
user_pref(
  "services.settings.main.search-categorization.last_check",
  1727482217,
);
user_pref("services.settings.main.search-config-icons.last_check", 1727482217);
user_pref(
  "services.settings.main.search-config-overrides-v2.last_check",
  1727482217,
);
user_pref("services.settings.main.search-config-v2.last_check", 1727482217);
user_pref(
  "services.settings.main.search-default-override-allowlist.last_check",
  1727482217,
);
user_pref("services.settings.main.search-telemetry-v2.last_check", 1727482217);
user_pref("services.settings.main.sites-classification.last_check", 1727482217);
user_pref("services.settings.main.tippytop.last_check", 1727482217);
user_pref("services.settings.main.top-sites.last_check", 1727482217);
user_pref("services.settings.main.translations-models.last_check", 1727482217);
user_pref("services.settings.main.translations-wasm.last_check", 1727482217);
user_pref(
  "services.settings.main.url-classifier-skip-urls.last_check",
  1727482217,
);
user_pref(
  "services.settings.main.urlbar-persisted-search-terms.last_check",
  1727482217,
);
user_pref(
  "services.settings.main.websites-with-shared-credential-backends.last_check",
  1727482217,
);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref(
  "signon.management.page.os-auth.optout",
  "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECDQGZ/7nvNysBAhxRBkShtAdmA==",
);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1727460232);
user_pref("toolkit.startup.last_success", 1727482214);
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.previousBuildID", "20240913135723");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref(
  "toolkit.telemetry.cachedClientID",
  "0a69c20e-6741-4bc8-85c6-b1d01d7001db",
);
user_pref(
  "toolkit.telemetry.cachedProfileGroupID",
  "11e24aa4-6f03-4fa9-8289-e27c4948d606",
);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
