apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 2 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - e2e-example
    build: $CI_COMMIT_SHORT_SHA
testcafe:
  version: 3.7.0
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./
suites:
  - name: "Browser Profile macOS"
    browserName: "firefox"
    src:
      - "tests/*.test.js"
    platformName: "macOS 12"
  - name: "Browser Profile Windows"
    browserName: "firefox"
    src:
      - "tests/*.test.js"
    platformName: "Windows 11"

env:
  SAUCE_FIREFOX_BROWSER_PROFILE: "firefox_test_profile"

reporters:
  spotlight: # Prints an overview of failed or otherwise interesting jobs.
    enabled: true
