name: saucectl testcafe tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Saucectl RUN Docker and Cloud
        uses: saucelabs/saucectl-run-action@v3
        with:
          concurrency: 10

  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Testcafe with Typescript
        uses: saucelabs/saucectl-run-action@v3
        with:
          working-directory: ./examples/typescript
          concurrency: 10
